import { Inter} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import { Toaster } from "@/components/ui/sonner";
const inter = Inter({subsets:['latin']})

export const metadata = {
  title: "AI-career coach",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      
    >
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${inter.className} `}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
          {/**header */}
          <Header/>
          <main className='min-h-screen'>{children}</main>            
          <Toaster richColors/>
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
